//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _014.RESOURCES {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_014.RESOURCES.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Selection Color.
        /// </summary>
        internal static string ChangeSelectionColor {
            get {
                return ResourceManager.GetString("ChangeSelectionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Point Markers.
        /// </summary>
        internal static string ClearPointMarkers {
            get {
                return ResourceManager.GetString("ClearPointMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Point.
        /// </summary>
        internal static string EdgePoint {
            get {
                return ResourceManager.GetString("EdgePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        internal static string Edges {
            get {
                return ResourceManager.GetString("Edges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Point.
        /// </summary>
        internal static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces.
        /// </summary>
        internal static string Faces {
            get {
                return ResourceManager.GetString("Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Point.
        /// </summary>
        internal static string MidPoint {
            get {
                return ResourceManager.GetString("MidPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Point.
        /// </summary>
        internal static string OriginPoint {
            get {
                return ResourceManager.GetString("OriginPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing.
        /// </summary>
        internal static string Probing {
            get {
                return ResourceManager.GetString("Probing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant.
        /// </summary>
        internal static string Quadrant {
            get {
                return ResourceManager.GetString("Quadrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Entities.
        /// </summary>
        internal static string SelectEntities {
            get {
                return ResourceManager.GetString("SelectEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Faces.
        /// </summary>
        internal static string SelectFaces {
            get {
                return ResourceManager.GetString("SelectFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Point.
        /// </summary>
        internal static string SelectPoint {
            get {
                return ResourceManager.GetString("SelectPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Face Normals.
        /// </summary>
        internal static string ShowFaceNormals {
            get {
                return ResourceManager.GetString("ShowFaceNormals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Selection Info.
        /// </summary>
        internal static string ShowSelectionInfo {
            get {
                return ResourceManager.GetString("ShowSelectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
